apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kwetter-user-frontend-ingress
  annotations:
kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: 35.201.94.81:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: kwetter-user-frontend
            port:
              number: 80