apiVersion: v1
kind: Service
metadata:
  name: kwetter-user-frontend
spec:
  selector:
    app: kwetter-user-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376